TOOL/controllers.py
from flask import request, render_template, Blueprint, json, redirect, url_for, flash
from app import db, login_manager
from models import User
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_required, login_user, current_user, logout_user
import random
import os
import pandas as pd
import config
from mod_datacleaning import data_cleaning

import linecache
import sys
def PrintException():
    exc_type, exc_obj, tb = sys.exc_info()
    f = tb.tb_frame
    lineno = tb.tb_lineno
    filename = f.f_code.co_filename
    linecache.checkcache(filename)
    line = linecache.getline(filename, lineno, f.f_globals)
    print ('EXCEPTION IN ({}, LINE {} "{}"): {}'.format(filename, lineno, line.strip(), exc_obj))
    return ('EXCEPTION IN ({}, LINE {} "{}"): {}'.format(filename, lineno, line.strip(), exc_obj))

mod_controllers = Blueprint('controllers', __name__)

@mod_controllers.route('/register', methods=['POST', 'GET'])
def register():
    if request.method == 'POST':
        try:
            user = User(request.form['name'], request.form['phone'], generate_password_hash(
                request.form['password'], method='sha256'), request.form['email'])
            db.session.add(user)
            db.session.commit()
            return redirect(url_for('controllers.login'))
        except Exception as e:
            print(e)
            flash('Wrong inputs, please check your input and try again.')
            return render_template('register.html', user=current_user)
    else:
        return render_template('register.html', user=current_user)


@login_manager.user_loader
def load_user(user_id):
    try:
        return User.query.get(int(user_id))
    except:
        return None


@mod_controllers.route('/login', methods=['POST', 'GET'])
def login():
    if request.method == 'GET':
        if not current_user.is_anonymous:
            return render_template('index.html', user=current_user)
        return render_template('login.html', user=current_user)
    else:
        user = User.query.filter(User.email == request.form['email']).first()
        if user:
            if check_password_hash(user.password, request.form['password']):
                login_user(user)
                return render_template('index.html', user=current_user)
            else:
                flash('Wrong password.')
                return render_template('login.html', user=current_user)
        else:
            flash('Username doesn\'t exist.')
            return render_template('login.html', user=current_user)


@mod_controllers.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    return redirect(url_for('controllers.index'))


@mod_controllers.route('/', methods=['GET'])
def index():
    return render_template('index.html', user=current_user)


@mod_controllers.route('/upload', methods=['POST'])
def upload():
    try:
        file = request.files['file']
        filename = file.filename
        if filename=='':
            raise ValueError('No file uploaded!!')
        file_uploads_path = os.path.join(config.UPLOADS_DIR, filename)
        file_static_path = os.path.join(config.STATIC_DIR, 'output')
        file_static_path = os.path.join(file_static_path, filename)
        file.save(file_uploads_path)
        if (filename.rsplit('.', 1)[1].lower() == 'csv'):
            dirty_file = pd.read_csv(file_uploads_path, sep=',', parse_dates=True)
            res = data_cleaning.id_classLabel_check(dirty_file)
            if(res!=True):
                raise ValueError(res)
            print('shape of dirty file:',dirty_file.shape)
            #missing_val_fixed_file = data_cleaning.fix_missing(dirty_file, request.form['fix'])
            missing_val_fixed_file = dirty_file
            print('shape of missing value fixed file:',missing_val_fixed_file.shape)
            #datelist=['DOB','DOD','DOD_HOSP','DOD_SSN']
            #cleaned_file=data_cleaning.handleDate(missing_val_fixed_file,datelist)
            cleaned_file=missing_val_fixed_file
            print('shape of cleaned file :',cleaned_file.shape)
            #cleaned_file = data_cleaning.clean(missing_val_fixed_file)
            #cleaned_file = missing_val_fixed_file
            describe=cleaned_file.describe()
            print(cleaned_file.dtypes)
            cleaned_file.to_csv(file_uploads_path, sep=',',index=False)
        elif (filename.rsplit('.', 1)[1].lower() == 'tsv'):
            dirty_file = pd.read_csv(file_uploads_path, sep='\t')
            missing_val_fixed_file = data_cleaning.fix_missing(
                dirty_file, request.form['fix'])
            cleaned_file = data_cleaning.clean(missing_val_fixed_file)
            cleaned_file.to_csv(file_uploads_path, sep=',',index=False)
        elif (filename.rsplit('.', 1)[1].lower() == 'json'):
            print (str(file_uploads_path))
            dirty_file = pd.read_json(str(file_uploads_path))
            missing_val_fixed_file = data_cleaning.fix_missing(
                dirty_file, request.form['fix'])
            cleaned_file = data_cleaning.clean(missing_val_fixed_file)
            cleaned_file.to_json(file_uploads_path)
        else:
            raise ValueError('Invalid file input! Please check the input file type')
        print(describe)
        download_path = 'static/uploads/' + filename
        #return render_template('success.html', download_path=download_path, user=current_user)

    
        return render_template('data_filter.html',title='visual tool',datasetPath=download_path, user=current_user)
    except Exception as e:
        print(e)
        PrintException()
        flash(PrintException())
        return render_template('index.html', user=current_user)

@mod_controllers.route('/contact', methods=['GET'])
def contact():
    print(current_user.name)
    return render_template('contact.html', user=current_user)


@login_required
@mod_controllers.route('/account', methods=['GET', 'POST'])
def account():
    if request.method == 'GET':
        colors = ['primary', 'success', 'info', 'warning', 'danger']
        return render_template('account.html', user=current_user, color=random.choice(colors))
    else:
        try:
            if check_password_hash(current_user.password, request.form['oldpassword']):
                current_user.password = generate_password_hash(
                    request.form['newpassword'], method='sha256')
                db.session.commit()
                return redirect(url_for('controllers.index'))
            else:
                flash('Enter current password correctly and try again.')
                return redirect(url_for('controllers.account'))
        except:
            flash('Some error occurred, please try again later.')
            return redirect(url_for('controllers.account'))

TOOL/templates/account.html
{% extends 'base.html' %}

{% block title %}
{{user.name}}
{% endblock %}

{% block active_account %}
active
{% endblock %}

{% block content %}
      <div class="container jumbotron" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-{{ color }}">{{user.name}}</h2>
        <p class="mb-4">
          Update your account details here.
        </p>
        <form action="{{ url_for('controllers.account') }}" method="POST">
          <div class="form-group">
            <label for="oldpassword">Old Password</label>
            <input name="oldpassword" type="password" class="form-control" id="oldpassword" aria-describedby="oldpassword" placeholder="Old password">
          </div>
          <div class="form-group">
            <label for="newpassword">New Password</label>
            <input name="newpassword" type="password" class="form-control" id="newpassword" aria-describedby="newpassword" placeholder="New password">
          </div>
          {% with messages = get_flashed_messages() %}
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
          <button type="submit" class="btn btn-{{ color }}">Update</button>
        </form>
      </div>
{% endblock %}

TOOL/templates/base.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}{% endblock %} | Visual Health Care Data Analytics</title>

    <!-- Bootstrap core CSS -->
    <link href="{{ url_for('static',filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{{ url_for('static',filename='css/portfolio-item.css') }}" rel="stylesheet">

    {% block import %}
    {% endblock %}
  </head>

  <body style="background-color: #fcfcfc;">

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{{ url_for('controllers.index') }}">VHAC</a>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item {% block active_index %}{% endblock %}">
            <a class="nav-link" href="{{ url_for('controllers.index') }}">Home</a>
          </li>
          <li class="nav-item {% block active_contact %}{% endblock %}">
            <a class="nav-link" href="{{ url_for('controllers.contact') }}">Contact Us</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item dropdown {% block active_account %}{% endblock %}">
            <a class="nav-link dropdown-toggle" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              {{ user.name }}
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="{{ url_for('controllers.account') }}">My Account</a>
              <a class="dropdown-item" href="{{ url_for('controllers.logout') }}">Logout</a>
            </div>
          </li>    
          {% else %}
          <li class="nav-item {% block active_login %}{% endblock %}">
            <a class="nav-link" href="{{ url_for('controllers.login') }}">Login</a>
          </li>
          {% endif %}
        </ul>
      </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container mt-5">
      {% block content %}
      {% endblock %}      
    </div>
    <div class="container-fluid mt-5">
      {% block content1 %}
      {% endblock %}      
    </div>

<br/>
    <footer class="py-3 bg-dark">
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{{ url_for('static',filename='vendor/jquery/jquery.min.js') }}"></script>
    <script src="{{ url_for('static',filename='vendor/bootstrap/js/bootstrap.bundle.min.js') }}"></script>
    {% block jsimport %}
    {% endblock %}
  </body>

</html>

TOOL/templates/contact.html
{% extends 'base.html' %}

{% block title %}
Contact Us
{% endblock %}

{% block active_contact %}
active
{% endblock %}

{% block content %}
      <div class="container jumbotron" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-info">Contact us</h2>
        <p>
          Submit your query or feedback here and hold back! We'll contact you.
        </p>
        <form>
          <div class="form-group">
            <label for="email">Email address</label>
            <input type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
          </div>
          <div class="form-group">
            <label for="message">Message</label>
            <textarea class="form-control" id="message" rows="3"></textarea>
          </div>
          <button type="submit" class="btn btn-info">Submit</button>
        </form>
      </button>
{% endblock %}

TOOL/templates/data_analysis.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}


{% block import %}
  <!--<link rel="shortcut icon" type="image/x-icon" href="docs/images/favicon.ico" />-->
  <link rel="stylesheet" href="{{ url_for('static',filename='vendor/leaflet/leaflet.css') }}"/>
  <script src="{{ url_for('static',filename='vendor/leaflet/leaflet.js') }}" ></script>
  <script src="{{ url_for('static',filename='vendor/d3/d3.v3.js') }}"></script>
  <script src="{{ url_for('static',filename='vendor/plotly/plotly-latest.min.js') }}"></script>
  <script src="{{ url_for('static',filename='js/data_analysis.js') }}"></script>
  <!--<link
    href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css"
    rel="stylesheet" type="text/css">
<link
    href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.13.min.css"
    rel="stylesheet" type="text/css">
<link
    href="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.css"
    rel="stylesheet" type="text/css">-->
    <style>
    .button {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 20px;
    text-align: center;
    text-decoration: none;
    display: inline-block;
    font-size: 16px;
    margin: 4px 2px;
}
.button5 {border-radius: 10%;}
p { font-weight: bold; }
</style>
{% endblock %}

{% block active_index %}
active
{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
  <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}
{% endwith %}
<!--<h4>Dataset :  '{{ datasetPath }}'</h4>-->

<h1 class="my-4">Matrix visualization</small></h1>
<div class="row">
   <!--<div id="includedContent"></div>-->
   <!--<div w3-include-html="{{ url_for('static',filename='static/output/myhtml.html') }} "></div>-->
   <iframe scrolling="yes" id="includedContent" src="{{ url_for('static',filename='output/myhtml.html') }}" style="width:100%; height: 400px;" frameBorder="0" scrolling="no">  </iframe>

 
</div>
{% endblock %}
{% block content1 %}
<div class="row">
<div class="col-md-2">
<div class="card">
  <div class="card-header">
 Example conditional Statements
  </div>
  <div class="card-body">
    <div id="dimlist" border="1"></div>
  </div>
  </div>
</div>
<div class="col-md-6">
        <div class="row">
          <div class="col-md-8">
            <div id='parent' style="width: 500px; height: 400px;"></div>
          </div>
          <div class="col-md-4">
            <div id="legend" style="overflow:scroll; height:400px;"></div>
          </div>
        </div>
</div>

<div class="col-md-4">
  <div class="card">
  <div class="card-header">
    Customize bit vector
  </div>
  <div class="card-body">
    <ul class="list-group list-group-flush" id="bitvector">
      <li class="list-group-item">Bit 0 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 1 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 2 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 3 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 4 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 5 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 6 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 7 : <input type="text" value="" /></li>
      <li class="list-group-item">Bit 8 : <input type="text" value="" /></li>
      

      <table><tr><td><li class="list-group-item">Bit 2 : <input type="text" value="" /></li></td><td><button class="button button5">+</button></td></tr></table>
      

    </ul>
    <br/>
    <button class="btn btn-primary" id="goButton">Get Image</a></button>
  </div>
</div>




</div>

<!--<h3 class="my-3">Project Description</h3>
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
  <h3 class="my-3">Project Details</h3>
  <ul>
    <li>Lorem Ipsum</li>
    <li>Dolor Sit Amet</li>
    <li>Consectetur</li>
    <li>Adipiscing Elit</li>
  </ul>
</div>
-->
</div>
<div class="row">
<div class="col-md-5">
    <div id="b1" border="1"></div>
  </div>
<div class="col-md-5">
    <div id="b2" border="1"></div>
  </div>
</div>
</div>
{% endblock %}

{% block jsimport %}
<!--<script src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.13.min.js"></script>
<script src="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.js"></script>-->
<!--<script src="{{ url_for('static',filename='output/myscript.js') }}"></script>-->
<script>
    var datasetPath='{{datasetPath}}';
    dynamicallyLoadSelectList('#dimlist',datasetPath);
    
    //$(function(){
    //  $("#includedContent").load('static/output/myhtml.html'); 
    //});
    $('#goButton').on('click',updateImage);
    $('#legend').on('click', 'td.backgroundcolor', function() {
      var color_val=$(this).attr('bgcolor');
      console.log(color_val);
      colorFilter('parent',color_val);
    });

</script>
{% endblock %}

TOOL/templates/index.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block active_index %}
active
{% endblock %}

{% block content %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<div class="alert alert-danger" role="alert">
  <p>{{ message }}</p>
</div>
{% endfor %}
{% endif %}
{% endwith %}
      <div class="row">
        <div class="col-md-4 col-sm-12">
          <div class="card" style="width: 20rem;">
            <div class="card-block">
              <h4 class="card-title text-center text-warning">CSV</h4>
              <p class="card-text text-center">Upload your .csv file here and get it cleaned</p>
              <form action="{{ url_for('controllers.upload') }}" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                  <input name="file" type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                  <small id="fileHelp" class="form-text text-muted">Upload your file here and click on the upload button</small>
                </div>
                <div class="form-group">
                  <label for="fix-missing">How to fix missing values?</label>
                  <select class="form-control" id="fix-missing" name="fix">
                    <option value="skip">Skip tuple/row</option>
                    <option value="mean">Replace by mean</option>
                    <option value="median">Replace by median</option>
                    <option value="max frequent">Replace by maximum frequent value</option>
                    <option value="max">Replace by maximum value</option>
                    <option value="min">Replace by minimum value</option>
                  </select>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-warning">Upload CSV</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-12">
          <div class="card" style="width: 20rem;">
            <div class="card-block">
              <h4 class="card-title text-center text-success">JSON</h4>
              <p class="card-text text-center">Upload your .json file here and get it cleaned</p>
              <form action="{{ url_for('controllers.upload') }}" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                  <input name="file" type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                  <small id="fileHelp" class="form-text text-muted">Upload your file here and click on the upload button</small>
                </div>
                <div class="form-group">
                  <label for="fix-missing">How to fix missing values?</label>
                  <select class="form-control" id="fix-missing" name="fix">
                    <option value="skip">Skip tuple/row</option>
                    <option value="mean">Replace by mean</option>
                    <option value="median">Replace by median</option>
                    <option value="max frequent">Replace by maximum frequent value</option>
                    <option value="max">Replace by maximum value</option>
                    <option value="min">Replace by minimum value</option>
                  </select>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-success">Upload JSON</button>
                </div>
              </form>
            </div>
          </div>
        </div>
        <div class="col-md-4 col-sm-12">
          <div class="card" style="width: 20rem;">
            <div class="card-block">
              <h4 class="card-title text-center text-info">TSV</h4>
              <p class="card-text text-center">Upload your .tsv file here and get it cleaned</p>
              <form action="{{ url_for('controllers.upload') }}" method="POST" enctype="multipart/form-data">
                <div class="form-group">
                  <input name="file" type="file" class="form-control-file" id="exampleInputFile" aria-describedby="fileHelp">
                  <small id="fileHelp" class="form-text text-muted">Upload your file here and click on the upload button</small>
                </div>
                <div class="form-group">
                  <label for="fix-missing">How to fix missing values?</label>
                  <select class="form-control" id="fix-missing" name="fix">
                    <option value="skip">Skip tuple/row</option>
                    <option value="mean">Replace by mean</option>
                    <option value="median">Replace by median</option>
                    <option value="max frequent">Replace by maximum frequent value</option>
                    <option value="max">Replace by maximum value</option>
                    <option value="min">Replace by minimum value</option>
                  </select>
                </div>
                <div class="text-center">
                  <button type="submit" class="btn btn-info">Upload TSV</button>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
{% endblock %}

TOOL/templates/login.html
{% extends 'base.html' %}

{% block title %}
Login
{% endblock %}

{% block active_login %}
active
{% endblock %}

{% block content %}
      <div class="container jumbotron" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-warning mb-4">Login</h2>
        <form action="{{ url_for('controllers.login') }}" method="POST">
          <div class="form-group">
            <label for="email">Email address</label>
            <input name="email" type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="message">Password</label>
            <input name="password" type="password" class="form-control" id="password" aria-describedby="password" placeholder="Password">
          </div>
          {% with messages = get_flashed_messages() %}
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
          <p>
            <a href="{{ url_for('controllers.register') }}">New to this site, want to register?</a>
          </p>
          <button type="submit" class="btn btn-warning">Submit</button>
        </form>
      </div>
{% endblock %}

TOOL/templates/register.html
{% extends 'base.html' %}

{% block title %}
Register
{% endblock %}

{% block active_login %}
active
{% endblock %}

{% block content %}
      <div class="container jumbotron" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-success mb-4">Register</h2>
        <form action="{{ url_for('controllers.register') }}" method="POST">
          <div class="form-group">
            <label for="email">Email address</label>
            <input name="email" type="email" class="form-control" id="email" aria-describedby="emailHelp" placeholder="Enter email">
          </div>
          <div class="form-group">
            <label for="name">Name</label>
            <input name="name" type="text" class="form-control" id="name" aria-describedby="nameHelp" placeholder="Enter name">
          </div>
          <div class="form-group">
            <label for="phone">Phone</label>
            <input name="phone" type="text" class="form-control" id="phone" aria-describedby="phoneHelp" placeholder="Enter phone number">
          </div>
          <div class="form-group">
            <label for="password">Password</label>
            <input name="password" type="password" class="form-control" id="password" aria-describedby="password" placeholder="Password">
          </div>
          {% with messages = get_flashed_messages() %}
          {% if messages %}
          {% for message in messages %}
          <div class="alert alert-danger" role="alert">
            {{ message }}
          </div>
          {% endfor %}
          {% endif %}
          {% endwith %}
          <button type="submit" class="btn btn-success">Submit</button>
        </form>
      </div>
{% endblock %}

TOOL/templates/success.html
{% extends 'base.html' %}

{% block title %}
Download
{% endblock %}

{% block content %}
      <div class="container jumbotron text-center" style="background-color: rgba(0.7,0.7,0.7,0.2)">
        <h2 class="text-success">Success!</h2>
        <p>
          Your file has been successfully cleaned. Click on the download button to download your file.
        </p>
        <a href="{{ download_path }}" download="" class="btn btn-outline-info btn-lg">Download your file!</a>
      </div>
{% endblock %}

TOOL/templates/test.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset='utf-8' />
    <meta http-equiv='content-type' content='text/html; charset=utf-8' />

    <title>Embed Demo</title>

    {{ resources|indent(4)|safe }}

    {{ plot_script|indent(4)|safe }}
  </head>
  <body>
    <!-- A simple form for changing the graph -->
    <p> Select your settings: </p>
    <form name="color_button" method='GET'>
        Color:
        <select name="color">
            <option {{ "selected" if color|indent(4)|safe == "Red" }} value="Red">Red</option>
            <option {{ "selected" if color|indent(4)|safe == "Green" }} value="Green">Green</option>
            <option {{ "selected" if color|indent(4)|safe == "Blue" }} value="Blue">Blue</option>
            <option {{ "selected" if color|indent(4)|safe == "Black" }} value="Black">Black</option>
        </select>
        <br>
        From:
        <input type="text" name="_from" value="{{ _from }}">
        <br>
        To:
        <input type="text" name="to" value="{{ to }}">
        <br>
        <button type="submit">Submit</button>
    </form>
    {{ plot_div|indent(4)|safe }}
    <p> Demonstrates some very simple embedding into a webpage</p>
  </body>
</html>